// Converts src/design/tokens.json into src/design/tokens.css (CSS custom properties).
// Light theme on :root; dark under [data-theme="dark"] and prefers-color-scheme: dark.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "src/design/tokens.json"), "utf8"));

const resolve = (v) => String(v).replace(/^\{([\w-]+)\}$/, "var(--$1)");

const light = [];
const dark = [];
for (const t of tokens.color.tokens) {
  if (typeof t.value === "object") {
    light.push([t.name, resolve(t.value.light)]);
    if (t.value.dark !== t.value.light) dark.push([t.name, resolve(t.value.dark)]);
  } else {
    light.push([t.name, resolve(t.value)]);
  }
}
for (const t of tokens.shadow.tokens) {
  light.push([t.name, t.value.light]);
  dark.push([t.name, t.value.dark]);
}

const shared = [];
for (const [k, v] of Object.entries(tokens.type.families)) shared.push([`font-${k}`, v]);
for (const g of tokens.type.groups) {
  for (const s of g.styles) {
    shared.push([`text-${s.name}-size`, s.fontSize]);
    shared.push([`text-${s.name}-leading`, s.lineHeight]);
    shared.push([`text-${s.name}-weight`, s.fontWeight]);
    if (s.letterSpacing) shared.push([`text-${s.name}-tracking`, s.letterSpacing]);
  }
}
for (const t of [...tokens.spacing.tokens, ...tokens.radius.tokens]) shared.push([t.name, t.value]);

const decls = (rows, pad) => rows.map(([k, v]) => `${pad}--${k}: ${v};`).join("\n");

const css = `/* Generated by scripts/tokens-to-css.mjs from src/design/tokens.json. Do not edit by hand. */

:root {
${decls(light, "  ")}
${decls(shared, "  ")}
  color-scheme: light;
}

:root[data-theme="dark"] {
${decls(dark, "  ")}
  color-scheme: dark;
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${decls(dark, "    ")}
    color-scheme: dark;
  }
}
`;
writeFileSync(join(root, "src/design/tokens.css"), css);
console.log(`tokens.css: ${light.length} light, ${dark.length} dark, ${shared.length} shared`);
