// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mocus_cpp_impl
List mocus_cpp_impl(IntegerVector gate_ids, IntegerVector gate_types, IntegerVector child_flat, IntegerVector child_start, IntegerVector child_end, int top_id);
RcppExport SEXP _tidyfault_mocus_cpp_impl(SEXP gate_idsSEXP, SEXP gate_typesSEXP, SEXP child_flatSEXP, SEXP child_startSEXP, SEXP child_endSEXP, SEXP top_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type gate_ids(gate_idsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gate_types(gate_typesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_flat(child_flatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_start(child_startSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type child_end(child_endSEXP);
    Rcpp::traits::input_parameter< int >::type top_id(top_idSEXP);
    rcpp_result_gen = Rcpp::wrap(mocus_cpp_impl(gate_ids, gate_types, child_flat, child_start, child_end, top_id));
    return rcpp_result_gen;
END_RCPP
}
// quantify_prob_cpp_impl
NumericVector quantify_prob_cpp_impl(NumericMatrix probs, IntegerMatrix truth_events, LogicalVector failure_rows);
RcppExport SEXP _tidyfault_quantify_prob_cpp_impl(SEXP probsSEXP, SEXP truth_eventsSEXP, SEXP failure_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type truth_events(truth_eventsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type failure_rows(failure_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(quantify_prob_cpp_impl(probs, truth_events, failure_rows));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tidyfault_mocus_cpp_impl", (DL_FUNC) &_tidyfault_mocus_cpp_impl, 6},
    {"_tidyfault_quantify_prob_cpp_impl", (DL_FUNC) &_tidyfault_quantify_prob_cpp_impl, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tidyfault(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
