#' gate() Function
#'
#' This internal function gathers all gate polygons for a set of supplied gate types and their x and y coordinates.
#' 
#' @param data (Required) data.frame of nodes with coordinates. Must include columns for `x` and `y` coordinates, and at least one row where the gate type is `"and"`, `"or"`, or `"top"`.
#' @param group (Default = `"id"`) Character string naming the column in `data` that contains unique identifiers for grouping nodes. Default is `"id"`.
#' @param gate (Default = `"type"`) Character string naming the column in `data` that contains gate types. Must contain values `"and"`, `"or"`, or `"top"`. Default is `"type"`.
#' @param size (Default = 1) Numeric value controlling the diameter of gate polygons. Larger values create bigger gate shapes.
#' @param res (Default = 50) Numeric value controlling the number of line segments used to draw curved gate shapes. Higher values create smoother curves but require more computation.
#' 
#' @return A data.frame (tibble) with columns `x` and `y` containing coordinate pairs that define gate polygon shapes. The data.frame is grouped by the `group` and `gate` columns, with one polygon per unique combination. Coordinates are centered at the node's position and scaled according to `size`.
#' 
#' @details This function generates polygon coordinates for visualizing gates in fault tree diagrams:
#'   \itemize{
#'     \item Filters nodes to only those with gate types (`"and"`, `"or"`, `"top"`)
#'     \item Groups nodes by their identifier and gate type
#'     \item Calls `get_gate()` for each group to generate the appropriate polygon shape
#'     \item Returns all polygon coordinates in a single data.frame suitable for use with `geom_polygon()` in ggplot2
#'   }
#'   The function is typically called internally by `illustrate()` but can be used directly to generate gate shapes for custom visualizations. Each gate type (AND, OR, top event) has a distinct shape generated by the corresponding `gate_*()` function.
#' 
#' @seealso \code{\link{get_gate}} for generating individual gate polygons, \code{\link{gate_and}} for AND gate shapes, \code{\link{gate_or}} for OR gate shapes, \code{\link{gate_top}} for top event shapes
#' 
#' @keywords fault tree gate polygon maker
#' @importFrom dplyr %>% rename filter group_by reframe
#' @importFrom rlang sym
#' @export

gate = function(data, group = "id", gate = "type", size = 1, res = 50){
  data %>%
    rename(group = !!sym(group), gate = !!sym(gate)) %>%
    filter(gate %in% c("and", "or", "top")) %>%
    group_by(group, gate) %>%
    reframe(get_gate(x, y, gate = gate, size = size, res = res))
}
