# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mocus_cpp_impl <- function(gate_ids, gate_types, child_flat, child_start, child_end, top_id) {
    .Call(`_tidyfault_mocus_cpp_impl`, gate_ids, gate_types, child_flat, child_start, child_end, top_id)
}

quantify_prob_cpp_impl <- function(probs, truth_events, failure_rows) {
    .Call(`_tidyfault_quantify_prob_cpp_impl`, probs, truth_events, failure_rows)
}

